### ISSUE TITLE
N++ v7.8.9 32-bit ... CTRL+F produces crash (non responsive)

### ISSUE THREAD

**Issue by TheArkive** [JetNpp/HexEditor#2]
The 32-bit plugin causes Notepad++ v7.8.9 32-bit to hang when pressing CTRL+F.  Not sure if there is meant to be CTRL+F search functionality.  If not, maybe disable / override this hotkey when Hex view mode is active?

**Comment by JetMeta** [comment]
Here is my env : win7 64 with service pack 1, notepad++ x86 (englisth)
I update notepad++ from v7.8.8 to v7.8.9, can't reproduce the issue.

This plugin only register one shortcut : ctrl + alt + shift + H. It did handle some message such as WM_CHAR/WM_KEYDOWN/WM_SYSKEYDOWN internally.

**Comment by TheArkive** [comment]
Ah ok, may be a conflict with another plugin then.  I'll mess around some more and try to find out.  My current env is Win 10 2004 64-bit, Notepad++ 32-bit v7.8.9

Current installed plugins:
* ComparePlugin
* ExtSettings
* FileSwitcher
* HexEditor
* MarkdownViewerPlusPlus
* mimeTools
* NppConverter
* NppExport
* NppTextFX
* RunMe
